Completed ex implementation
EligeBader/ds-mod-1-1024-code-solutions pull request #33
Opened 2024-12-10 01:03 UTC by EligeBader

2024-12-10 19:13 UTC, Svangorden13 commented on implementation/helper_functions.py
> +def split_data(df, target, feature_selected= None, features =[]):
Maybe rename "features" to "features_dropped"

2024-12-10 19:25 UTC, Svangorden13 commented
Use name other than "train_model" for the actual model (since this is already the name of the function used for training)

2024-12-10 19:27 UTC, Svangorden13 requested changes

2024-12-10 19:27 UTC, Svangorden13 commented on implementation/helper_functions.py
> +    numeric_imputer = SimpleImputer(strategy='median')
These imputer objects should be saved and re-used for the test data, like what you did for encode_data()

2024-12-10 19:27 UTC, Svangorden13 commented on implementation/helper_functions.py
> +    X_new = df.drop(columns=features)
The data should already be dropped and fully handled by the time you reach the predict stage so I don't think this is totally necessary. Your call though. However, I would again change "features" to "features_dropped".

2024-12-10 19:27 UTC, Svangorden13 commented on implementation/helper_functions.py
> +def encode_data(df, target, categorical_cols, train):
Would be nice to see this expanded to use multiple encoding schemes

2024-12-12 23:29 UTC, Svangorden13 commented on implementation/helper_functions.py
> +def split_data(df, target,target_dropped, feature_selected= None):
features_dropped, not target_dropped

2024-12-12 23:40 UTC, Svangorden13 requested changes

2024-12-12 23:40 UTC, Svangorden13 commented on implementation/helper_functions.py
> +        # Initialize and fit encoders
Use a single TargetEncoder() and single OrdinalEncoder()

2025-01-08 01:11 UTC, Svangorden13 approved these changes

2025-01-14 23:51 UTC, Svangorden13 requested changes

2025-01-14 23:51 UTC, Svangorden13 commented on implementation/helper_functions-Class.py
> +        mod = model()
Does this assume the encoder will not create additional columns (e.g. OneHot or Hashing)?

2025-01-14 23:51 UTC, Svangorden13 commented on implementation/helper_functions-Class.py
> +        if features_to_scale is None:
This will only scale the data if features_to_scale is None

2025-01-15 17:42 UTC, EligeBader commented on implementation/helper_functions-Class.py
> +        mod = model()
yes, I usually don't use OneHot or Hashing Encoders, so I didn't think about what if some columns were added

2025-01-30 19:42 UTC, Svangorden13 commented on implementation/helper_functions-Class.py
> +            tempvar = mod.transform(df[categorical_cols])
You could actually move this and the corresponding block of code in the else outside the if-else since its doing the same thing

2025-01-30 19:44 UTC, Svangorden13 approved these changes

2025-01-30 22:33 UTC, merged